version: "3.3"


services:
  traefik:
    image: traefik
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    networks:
      - rede-externa
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.localhost`)
      - traefik.http.routers.api.service=api@internal


  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: maratona
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      TZ: GMT-4
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - rede-interna

  flyway:
    image: dhoer/flyway:alpine
    command: -url=jdbc:postgresql://postgres:5432/maratona -schemas=public -user=postgres -password=admin migrate
    volumes:
      - ./migrations/migrations:/flyway/sql
    depends_on:
      - postgres
    networks:
      - rede-interna

  seeder:
    build:
      context: ./migrations
    depends_on:
      - flyway
    networks:
      - rede-interna

  pgadmin:
    image: dpage/pgadmin4
    environment:
      POSTGRES_USER: postgres
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_HOST:
    depends_on:
      - postgres
    networks:
      - rede-interna
      - rede-externa
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.rule=Host(`pg.localhost`)
      - traefik.http.routers.pgadmin.entrypoints=web

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - broker


  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - broker
      - rede-interna
    ports:
      - 29092:29092

  producer:
    build:
      context: ./producer
    depends_on:
      - postgres
    networks:
      - rede-externa
    labels:
      - traefik.enable=true
      - traefik.http.routers.producer.rule=Host(`localhost`)
      - traefik.http.routers.producer.entrypoints=web

  questao-job:
    build:
      context: ./consumers/questao-job
    depends_on:
      - kafka
    networks:
      - rede-interna

  teste-job:
    build:
      context: ./consumers/test-job
    depends_on:
      - kafka
    networks:
      - rede-interna

networks:
  rede-interna:
  rede-externa:
  broker:
