version: "3.7"

services:
  postgres:
    image: postgres
    container_name: "postgres"
    environment:
      - POSTGRES_DB=maratona
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    networks: 
      - postgres-network

  pg-admin:
    image: dpage/pgadmin4
    environment:
      POSTGRES_USER: "postgres"
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

networks: 
  postgres-network:
    driver: bridge