version: "3.3"

services:
  traefik:
    image: "traefik"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    networks: 
      - web
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.api.service=api@internal"

  postgres:
    image: postgres
    container_name: "postgres"
    environment:
      - POSTGRES_DB=maratona
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    networks: 
      - postgres-network

  pg-admin:
    image: dpage/pgadmin4
    container_name: "pgadmin4"
    environment:
      POSTGRES_USER: "postgres"
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - postgres
    networks:
      - postgres-network
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pg.localhost`)"
      - "traefik.http.routers.pgadmin.entrypoints=web"

  zookeeper:
    container_name: "zookeeper"
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    container_name: "kafka"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181


  producer:
    container_name: "producer_nestjs"
    build:
      dockerfile: Dockerfile
      context: ./producer
    depends_on:
      - postgres
    networks: 
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.producer.rule=Host(`localhost`)"
      - "traefik.http.routers.producer.entrypoints=web"
      

networks: 
  postgres-network:
    driver: bridge
  web:
    driver: bridge